#Faster live reload
quarkus.live-reload.instrumentation=true

# Frontend dev
quarkus.quinoa.package-manager-install=true
quarkus.quinoa.package-manager-install.node-version=20.11.0
quarkus.quinoa.enable-spa-routing=true
quarkus.quinoa.ignored-path-prefixes=/api

# Dev overrides
%dev.quarkus.log.category."com.lunatech.pointingpoker".level=DEBUG