name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JVM
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: test coverage
        run: sbt qa

      - name: Codecov
        uses: codecov/codecov-action@v2.1.0

  style-check:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JVM
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: styleCheck
        run: sbt styleCheck
