name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JVM
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - uses: sbt/setup-sbt@v1
      
      - name: test coverage
        run: sbt qa

      - name: Codecov
        uses: codecov/codecov-action@v5

  style-check:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JVM
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - uses: sbt/setup-sbt@v1

      - name: styleCheck
        run: sbt styleCheck
